spring:
  application:
    name: service-job
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
      discovery:
        enabled: true
        register: true
server:
  port: 8098